In [2]:
# Import Numpy
import numpy as np

Create a 1D Numpy array from a Python list.

In [3]:
one_d = np.array([2,4,6,8])

In [4]:
one_d

array([2, 4, 6, 8])

In [5]:
# Check array type
print(type(one_d))

<class 'numpy.ndarray'>


In [6]:
# Check dimensions
print(one_d.ndim)

1


In [7]:
# Check Shape
print(one_d.shape)

(4,)


In [8]:
# Check datatype
print(one_d.dtype)

int64


In [9]:
# Perform verctorized operation
print(one_d + 2)
print(one_d * 3)

[ 4  6  8 10]
[ 6 12 18 24]


Create a 2D array of shape (3,3).

In [10]:
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(two_d.ndim)

2


In [12]:
print(two_d.shape)

(3, 3)


In [13]:
# first row
print(two_d[0])

[1 2 3]


In [14]:
# second row
print(two_d[1])

[4 5 6]


In [15]:
# first element
print(two_d[0,0])

1


In [16]:
# second column
print(two_d[:,1])

[2 5 8]


create a 3D array with two 2 * 2 matrices.

In [17]:
three_D = np.array([[[4, 7],[9, 3]]])
three_D

array([[[4, 7],
        [9, 3]]])

In [18]:
import sys
import numpy as np
import pandas as pd

print(sys.version)
print(np.__version__)
print(pd.__version__)

3.14.5 (v3.14.5:5607950ef23, May 10 2026, 07:38:09) [Clang 21.0.0 (clang-2100.0.123.102)]
2.4.4
3.0.2


In [19]:
print(three_D.ndim)

3


In [20]:
print(three_D.shape)

(1, 2, 2)


Find total number of elemets in and array.

In [21]:
th_d = np.array([[[2,5,3,5],[4,7,1,9], [3,2,7,8]]])
th_d

array([[[2, 5, 3, 5],
        [4, 7, 1, 9],
        [3, 2, 7, 8]]])

In [22]:
print(th_d.size)

12


In [23]:
th_d.shape

(1, 3, 4)

In [24]:
print(th_d.ndim)

3


In [25]:
print(th_d.dtype)

int64


Create an array filled with zeros.

In [26]:
zD = np.array([0,0,0,0])
zD

array([0, 0, 0, 0])

In [27]:
zD = np.zeros(4)
zD

array([0., 0., 0., 0.])

In [28]:
print(zD.ndim)

1


create an array filled with ones.

In [29]:
o_arr = np.ones((4,3))
o_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

create identity matrix of size 4 * 4

In [30]:
ide = np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Convert a 1D array into: row vector, column vector

In [34]:
one_D = np.array([2,3,5,7])
print(one_D)

# Row Vector
row_vector = one_D.reshape(1, -1)
print(row_vector)

# Colum Vector
column_vector = one_D.reshape(-1, 1)
print(column_vector)

[2 3 5 7]
[[2 3 5 7]]
[[2]
 [3]
 [5]
 [7]]


Reshape array of 12 elements into:
(3,4)
(2,6)
(2,2,3)

In [37]:
arr = np.arange(1,13)
print(arr)

# Reshape into (3,4)
a = arr.reshape(3,4)
print(a)

# Reshape into (2,6)
b = arr.reshape(2,6)
print(b)

# Reshape into (2,2,3)
c = arr.reshape(2,2,3)
print(c)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Create array using arange() from 1-50


In [38]:
arr1 = np.arange(1,50)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Create evenly spaced values using linspace().


In [39]:
arr2 = np.linspace(2,50, 20)
arr2

array([ 2.        ,  4.52631579,  7.05263158,  9.57894737, 12.10526316,
       14.63157895, 17.15789474, 19.68421053, 22.21052632, 24.73684211,
       27.26315789, 29.78947368, 32.31578947, 34.84210526, 37.36842105,
       39.89473684, 42.42105263, 44.94736842, 47.47368421, 50.        ])

Create random integer array of shape (4,5).

In [41]:
arr3 = np.random.randint(1, 100, size = (4, 5))
arr3

array([[56, 19, 19,  7, 91],
       [57,  5, 43, 76, 82],
       [48, 39, 90, 19,  8],
       [ 5, 12, 81, 35, 71]])

Find: ndim, size, shape, itemsize

In [42]:
# ndim
print(arr3.ndim)
# size
print(arr3.size)
# shape
print(arr3.shape)
# itemsize
print(arr3.itemsize)

2
20
(4, 5)
8


Flatten a 2D array.

In [43]:
# Create 2D array
arr4 = np.array([[1,2,3],[4,5,6]])
print("Original Array: \n", arr3)

# Flatten 
flat_arr = arr4.flatten()
print("\nFlattened Array: \n", flat_arr)


Original Array: 
 [[56 19 19  7 91]
 [57  5 43 76 82]
 [48 39 90 19  8]
 [ 5 12 81 35 71]]

Flattened Array: 
 [1 2 3 4 5 6]


Convert flattened array back to 2D

In [44]:
arr_2d = flat_arr.reshape(2,3)
print("2D Array: \n", arr_2d)

2D Array: 
 [[1 2 3]
 [4 5 6]]


Transpose a matrix.

In [46]:
# Create matrix
arr5 = np.array([[1,2,3,4],[5,6,7,8]])
print("Original Matrix: \n", arr5)

# Transpose matrix
transpose_arr = arr5.T
print("\n Transposed Matrix:\n", transpose_arr)

Original Matrix: 
 [[1 2 3 4]
 [5 6 7 8]]

 Transposed Matrix:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


Create 4D array and inspect dimensions.

In [49]:
arr6 = np.array([
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
    ],
    [
        [[9,10],[11,12]],
        [[13,14],[15,16]]
    ]
])
print("4D Array:\n", arr6)

# Inspect dimesions
print("\nndim:", arr6.ndim)
print("shape:", arr6.shape)
print("size:",arr6.size)

4D Array:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

ndim: 4
shape: (2, 2, 2, 2)
size: 16
